apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sensu-go-slack-bot.fullname" . }}
  labels:
{{ include "sensu-go-slack-bot.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sensu-go-slack-bot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sensu-go-slack-bot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "{{ .Values.service.port }}"
        prometheus.io/path: "{{ .Values.metricsPathEndpoint }}"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SENSU_USER
            value: "{{ .Values.sensuUser }}"
          - name: SENSU_URL
            value: "{{ .Values.sensuURL }}"
          - name: SLACK_CHANNEL
            value: "{{ .Values.slackChannel }}"
          - name: SENSU_SECRET
            valueFrom: 
              secretKeyRef:
                name: sensu
                key: sensuSecret
          - name: SLACK_TOKEN
            valueFrom: 
              secretKeyRef:
                name: sensu
                key: slackToken
          - name: SLACK_SIGNING_SECRET
            valueFrom:
              secretKeyRef:
                name: sensu
                key: slackSigningSecret
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.testPathEndpoint }}
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.testPathEndpoint }}
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
