apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensu-go-slack-bot.fullname" . }}
  labels:
{{ include "sensu-go-slack-bot.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sensu-go-slack-bot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
