language: go
go:
- 1.13.x

services: 
  - docker

install:
- go get gopkg.in/alecthomas/gometalinter.v1
- go get github.com/gordonklaus/ineffassign
- go get github.com/jgautheron/goconst/cmd/goconst
- go get github.com/kisielk/errcheck
- go get github.com/golang/dep/cmd/dep
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- dep ensure
script:
- gometalinter.v1 --vendor --disable-all --enable=vet --enable=ineffassign
  --enable=goconst --tests ./...
- go test -v -race ./...
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
- docker build -f Dockerfile -t betorvs/sensu-go-slack-bot:$COMMIT .

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push betorvs/sensu-go-slack-bot:$COMMIT
